name: Importar
on:
  push:
    branches: [ main ]
    paths: [ 'apis/**' ]

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Instalar apictl (mantengo tu versión 4.3.3)
    - name: Instalar apictl
      run: |
        FILE="apictl-4.3.3-linux-amd64.tar.gz"
        curl -Lf -o "$FILE" \
          https://github.com/wso2/product-apim-tooling/releases/download/v4.3.3/"$FILE"
        tar -xzf "$FILE"
        sudo install -m 755 apictl/apictl /usr/local/bin/apictl
        apictl version

    # Añadir entorno vía túnel + login
    - name: Login APIM
      env:
        APIM_ENDPOINT:       ${{ secrets.APIM_ENDPOINT }}
        APIM_TOKEN_ENDPOINT: ${{ secrets.APIM_TOKEN_ENDPOINT }}
        APIM_USER:           ${{ secrets.APIM_USER }}
        APIM_PASS:           ${{ secrets.APIM_PASS }}
      run: |
        apictl add env dev-env \
          --apim  "$APIM_ENDPOINT" \
          --token "$APIM_TOKEN_ENDPOINT" \
          --insecure
        apictl login dev-env -u "$APIM_USER" -p "$APIM_PASS" -k

    # Importar OAS → estado CREATED y SIN despliegue
    - name: Importar working copy (CREATED)
      run: |
        shopt -s globstar nullglob
        for oas in apis/**/api.yaml; do
          base_dir=$(dirname "$oas")
          api_name=$(basename "$(dirname "$base_dir")")
          api_version=$(basename "$base_dir")
          proj="/tmp/${api_name}_${api_version}"
          rm -rf "$proj"

          # --initial-state=CREATED   ==> ciclo de vida queda en CREATED
          apictl init "$proj" --oas "$oas" --initial-state=CREATED

          # --skip-deployments        ==> NO crea ni despliega revisión
          apictl import api -f "$proj" -e dev-env \
            --update --skip-deployments -k
        done